# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box              = "centos/7"
  config.vm.box_check_update = false
  config.vm.hostname         = "hacklab.localdomain"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "public_network", bridge: "enx00a0c6000000"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    #yum update
    echo "hello world" > /opt/hello.txt
  SHELL
 
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
